Repository PharmaTechVe/pharmatech-sdk, pull requests merged in 2025-04, with the labels that each got.

#35 feature/API-39/update-password-with-current-password
  src/auth.ts
Labels: documentation, feature

#36 hotfix/refactor-exports
  package.json
  src/client.ts
  src/errors.ts
  src/errors/api-error.ts
  src/errors/index.ts
  src/index.ts
  src/product-presentation.ts
  src/product.ts
  src/services/auth.ts
  src/services/branch.ts
  src/services/category.ts
  src/services/city.ts
  src/services/country.ts
  src/services/generic-product.ts
  src/services/index.ts
  src/services/inventory.ts
  src/services/manufacturer.ts
  src/services/presentation.ts
  src/services/product-image.ts
  src/services/product-presentation.ts
  src/services/product.ts
  src/services/promo.ts
  src/services/state.ts
  src/services/user-address.ts
  src/services/user.ts
  src/tests/api.test.ts
  src/types/auth.ts
  src/types/branch.ts
  src/types/category.ts
  src/types/city.ts
  src/types/country.ts
  src/types/generic-product.ts
  src/types/index.ts
  src/types/inventory.ts
  src/types/manufacturer.ts
  src/types/presentation.ts
  src/types/product-image.ts
  src/types/product-presentation.ts
  src/types/product.ts
  src/types/promo.ts
  src/types/state.ts
  src/types/user-address.ts
  src/types/user.ts
  src/types/utils.ts
Labels: documentation, feature

#39 feature/add-start-at-promo
  src/types/promo.ts
Labels: feature

#40 Release 0.4.0
  package.json
  src/client.ts
  src/errors.ts
  src/errors/api-error.ts
  src/errors/index.ts
  src/index.ts
  src/product-presentation.ts
  src/product.ts
  src/services/auth.ts
  src/services/branch.ts
  src/services/category.ts
  src/services/city.ts
  src/services/country.ts
  src/services/generic-product.ts
  src/services/index.ts
  src/services/inventory.ts
  src/services/manufacturer.ts
  src/services/presentation.ts
  src/services/product-image.ts
  src/services/product-presentation.ts
  src/services/product.ts
  src/services/promo.ts
  src/services/state.ts
  src/services/user-address.ts
  src/services/user.ts
  src/tests/api.test.ts
  src/types/auth.ts
  src/types/branch.ts
  src/types/category.ts
  src/types/city.ts
  src/types/country.ts
  src/types/generic-product.ts
  src/types/index.ts
  src/types/inventory.ts
  src/types/manufacturer.ts
  src/types/presentation.ts
  src/types/product-image.ts
  src/types/product-presentation.ts
  src/types/product.ts
  src/types/promo.ts
  src/types/state.ts
  src/types/user-address.ts
  src/types/user.ts
  src/types/utils.ts
Labels: documentation, feature

#44 hotifx/get-product-response
  src/types/product.ts
Labels: bug

#45 Release 0.4.1
  package-lock.json
  package.json
  src/index.ts
  src/services/branch.ts
  src/services/category.ts
  src/services/coupon.ts
  src/services/generic-product.ts
  src/services/index.ts
  src/services/user.ts
  src/tests/api.test.ts
  src/types/branch.ts
  src/types/coupon.ts
  src/types/generic-product.ts
  src/types/index.ts
  src/types/product.ts
  src/types/user.ts
  src/types/utils.ts
Labels: feature

#47 feature/API-40/order-service
  src/services/order.ts
  src/types/generic-product.ts
  src/types/index.ts
  src/types/order.ts
  src/types/product-presentation.ts
Labels: feature

#48 Feature/api 47/add filter get products
  src/services/product.ts
  src/types/product.ts
Labels: feature

#46 Features/API-44/payment-methods
  src/index.ts
  src/services/index.ts
  src/services/payment-confirmation.ts
  src/services/payment-information.ts
  src/types/index.ts
  src/types/payment-confirmation.ts
  src/types/payment-information.ts
Labels: feature

#49 Release 0.4.2
  package.json
  src/index.ts
  src/services/index.ts
  src/services/order.ts
  src/services/payment-confirmation.ts
  src/services/payment-information.ts
  src/services/product.ts
  src/types/generic-product.ts
  src/types/index.ts
  src/types/order.ts
  src/types/payment-confirmation.ts
  src/types/payment-information.ts
  src/types/product-presentation.ts
  src/types/product.ts
Labels: documentation, feature

#53 hotfix/optional-range-price
  src/services/product.ts
Labels: bug

#54 Release 0.4.3
  package.json
  src/index.ts
  src/services/index.ts
  src/services/notification.ts
  src/services/product.ts
  src/types/index.ts
  src/types/notification.ts
Labels: bug

#51 Feature/api 42/delivery management sdk
  src/index.ts
  src/services/delivery.ts
  src/services/index.ts
  src/types/delivery.ts
  src/types/index.ts
Labels: feature

#52 Feat(API-45): profile-delivery-sdk
  src/index.ts
  src/services/index.ts
  src/services/profile-delivery.ts
  src/types/index.ts
  src/types/profile-delivery.ts
Labels: feature

#55 hotfix/missing-product-image-methods
  src/services/product-image.ts
  src/types/product-image.ts
Labels: bug

#56 Release 0.4.4
  package.json
  src/index.ts
  src/services/branch.ts
  src/services/delivery.ts
  src/services/index.ts
  src/services/manufacturer.ts
  src/services/presentation.ts
  src/services/product-image.ts
  src/services/product-presentation.ts
  src/services/profile-delivery.ts
  src/types/delivery.ts
  src/types/index.ts
  src/types/order.ts
  src/types/product-image.ts
  src/types/product-presentation.ts
  src/types/profile-delivery.ts
Labels: documentation, feature

#59 Release 0.4.5
  package.json
  src/index.ts
  src/services/index.ts
  src/services/product-category.ts
  src/types/delivery.ts
Labels: documentation, feature

#60 Release 0.4.6
  package.json
  src/index.ts
  src/services/product.ts
  src/types/delivery.ts
  src/types/order.ts
  src/types/product.ts
Labels: documentation, feature

#62 Release 0.4.7
  package.json
  src/index.ts
  src/services/delivery.ts
  src/services/order.ts
  src/types/delivery.ts
Labels: feature

#65 Release 0.4.9
  package.json
  src/index.ts
  src/types/delivery.ts
Labels: feature

#66 Release 0.4.10
  package.json
  src/index.ts
  src/services/coupon.ts
  src/services/presentation.ts
  src/services/product.ts
  src/services/promo.ts
  src/types/coupon.ts
  src/types/delivery.ts
  src/types/product.ts
  src/types/promo.ts
  src/types/user-address.ts
Labels: feature

#67 Release 0.4.11
  package.json
  src/index.ts
  src/services/bank.ts
  src/services/index.ts
  src/types/product-presentation.ts
Labels: feature
