Repository PharmaTechVe/pharmatech-sdk, pull requests merged in 2025-03, with the labels that each got.

#5 hotfix/add-dev-mode
  src/auth.ts
  src/client.ts
  src/index.ts
  src/settings.ts
  src/tests/api.test.ts
Labels: bug

#8 Fix set localhost and update version
  package.json
  src/index.ts
  src/settings.ts
  src/tests/api.test.ts
Labels: bug

#9 Features/api-14/add-get-products-endpoint
  package.json
  src/client.ts
  src/index.ts
  src/product.ts
  src/settings.ts
  src/tests/api.test.ts
  src/utils/models.ts
Labels: feature

#10 feat API-8: add sign up sdk and sign up test
  package-lock.json
  src/auth.ts
  src/tests/api.test.ts
Labels: feature

#11 feature/update-and-forgot-password
  src/auth.ts
  src/client.ts
  src/tests/api.test.ts
Labels: feature

#13 Release 0.2.0
  package-lock.json
  package.json
  src/auth.ts
  src/client.ts
  src/index.ts
  src/product.ts
  src/tests/api.test.ts
  src/utils/models.ts
Labels: feature

#18 feature/add-catalogs-functions
  .husky/pre-commit
  .lintstagedrc
  README.md
  package-lock.json
  package.json
  src/auth.ts
  src/branch.ts
  src/category.ts
  src/city.ts
  src/client.ts
  src/country.ts
  src/errors.ts
  src/index.ts
  src/manufacturer.ts
  src/presentation.ts
  src/product.ts
  src/state.ts
  src/tests/api.test.ts
  src/user.ts
Labels: documentation, feature

#19 Release 0.3.0
  .husky/pre-commit
  .lintstagedrc
  README.md
  package-lock.json
  package.json
  src/auth.ts
  src/branch.ts
  src/category.ts
  src/city.ts
  src/client.ts
  src/country.ts
  src/errors.ts
  src/index.ts
  src/manufacturer.ts
  src/presentation.ts
  src/product.ts
  src/state.ts
  src/tests/api.test.ts
  src/user.ts
Labels: documentation, feature

#21 Release 0.3.1
  package.json
  src/client.ts
  src/index.ts
  src/tests/api.test.ts
Labels: bug

#24 feature/API-23/generic-product-service
  src/generic-product.ts
  src/index.ts
Labels: feature

#25 hotfix/add-jwt-and-missing-services
  package.json
  src/auth.ts
  src/index.ts
  src/tests/api.test.ts
  src/user.ts
Labels: bug

#27 Release 0.3.2
  package.json
  src/auth.ts
  src/generic-product.ts
  src/index.ts
  src/inventory.ts
  src/promo.ts
  src/tests/api.test.ts
  src/user-address.ts
  src/user.ts
Labels: documentation, feature

#29 Release 0.3.4
  package.json
  src/generic-product.ts
  src/index.ts
  src/product-image.ts
  src/product-presentation.ts
  src/tests/api.test.ts
Labels: feature

#30 Release 0.3.5
  package.json
  src/index.ts
  src/product.ts
  src/tests/api.test.ts
Labels: feature

#31 Release 0.3.6
  package.json
  src/index.ts
  src/tests/api.test.ts
  src/user.ts
Labels: feature

#32 Release 0.3.7
  package.json
  src/index.ts
  src/tests/api.test.ts
Labels: documentation
